language: rust
sudo: false
env:
  global:
    - RUST_BACKTRACE=1
    - CLIPPY_VERSION=0.0.192
    - RUSTFLAGS="-D warnings"
cache: cargo

rust:

matrix:
  include:
  # This build uses stable and checks rustfmt (clippy is not on stable).
  - rust: stable
    install:
      - rustup component add rustfmt-preview
  # This build uses the nightly used by TiKV and checks both rustfmt & clippy.
  - rust: nightly-2018-04-06
    install:
      - export PATH="$PATH:$HOME/.cargo/bin"
      - rustup component add rustfmt-preview
      - if [[ `cargo clippy -- --version` != $CLIPPY_VERSION* ]]; then cargo install -f clippy --version $CLIPPY_VERSION; fi

script:
  - if `which cargo-fmt &>/dev/null`; then cargo fmt --all -- --write-mode diff; fi
  - if `which cargo-clippy &>/dev/null`; then cargo clippy; fi
  - cargo test --all -- --nocapture
