[package]
name = "raft-proto"
version = "0.1.0"
authors = ["The TiKV Project Developers"]
edition = "2018"
license = "Apache-2.0"
keywords = ["raft", "distributed-systems", "ha"]
repository = "https://github.com/pingcap/raft-rs"
homepage = "https://github.com/pingcap/raft-rs"
documentation = "https://docs.rs/raft-proto"
description = "Protocol definitions for the rust language implementation of the Raft algorithm."
categories = ["algorithms", "database-implementations"]
build = "build.rs"

[features]
default = ["repr-protobuf"]
repr-protobuf = ["protobuf", "jinkela-build/repr-protobuf", "jinkela/repr-protobuf"]
repr-prost = ["prost", "jinkela-build/repr-prost", "bytes", "quick-error", "jinkela/repr-prost"]

[build-dependencies]
jinkela-build = { git = "https://github.com/busyjay/jinkela" }

[dependencies]
bytes = { version = "0.4.11", optional = true }
lazy_static = "1.3.0"
prost = { version = "0.5", optional = true }
protobuf = { version = "2", optional = true }
quick-error = { version = "1.2", optional = true }
jinkela = { git = "https://github.com/busyjay/jinkela" }